name: geo
channels:
  - dnachun
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - backoff=1.11.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.7.22
  - cairo=1.18.0
  - certifi=2023.7.22
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - greenlet=3.0.1
  - hdf4=4.2.15
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - json-c=0.17
  - jupysql=0.10.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kealib=1.5.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libboost-headers=1.82.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgdal=3.7.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libuv=1.46.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.6
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - monotonic=1.5
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nodejs=20.8.1
  - nspr=4.35
  - nss=3.94
  - openjpeg=2.5.0
  - openssl=3.1.4
  - packaging=23.2
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=4.0.0
  - ploomber-core=0.2.16
  - poppler=23.11.0
  - poppler-data=0.4.12
  - postgis=3.4.0
  - postgresql=16.1
  - posthog=3.0.2
  - prettytable=3.9.0
  - proj=9.3.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python_abi=3.12
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - soci-core=4.0.3
  - soci-postgresql=4.0.3
  - sql-language-server=1.6.0
  - sqlalchemy=2.0.23
  - sqlglot=19.5.1
  - sqlite=3.44.0
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - tiledb=2.16.3
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzcode=2023c
  - tzdata=2023c
  - uriparser=0.9.7
  - urllib3=2.1.0
  - wcwidth=0.2.10
  - wheel=0.41.3
  - xerces-c=3.2.4
  - xeus=3.0.5
  - xeus-sql=0.2.1
  - xeus-zmq=1.0.
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xvega=0.0.10
  - xvega-bindings=0.0.10
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
prefix: /home/jovyan/.conda/geo
